name: mx_asset_path_generator
description: 生成資源路徑
version: 1.0.1
repository: https://github.com/MagicalWater/mx_asset_path_generator

environment:
  sdk: ^3.3.4

dependencies:
  path: ^1.8.0
  collection: ^1.18.0
  dart_style: ^2.3.6
  args: ^2.3.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  mx_asset_path_generator:
